### ISSUE TITLE
Support Search Term Query Option

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-api#41]

**Comment by KamillaKhabibrakhmanova** [comment]
I'll start on this one

**Comment by aaghevli** [comment]
Hey @KamillaKhabibrakhmanova, some of this work has been done using the odata-v4-mongodb library to conform with odata and some of the date and implemented on the client on [#83](https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/83/files#diff-49a7b77b39ca8203b3c8e9b710e1a444R5)

It did expose an issue that may be due to the specific library thought, so I opened an [issue to track[(https://github.com/ResistanceCalendar/resistance-calendar-api/issues/45)

```
const filter = createFilter(query.$filter);
console.log('mongo db filter from odata: ' + JSON.stringify(filter));
```

**Comment by aaghevli** [comment]
I filed a PR to see if the source library can be fixed: 

https://github.com/jaystack/odata-v4-mongodb/pull/4

**Comment by aaghevli** [comment]
This has been fixed
